
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/dev/Dockerfile
    environment:
      - APP_ENV=local
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/app
    container_name: tg_music_app
